import { ClientProviders } from "@/utils/ClientProviders";
import { Container } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "AppDev - Hack'n'Slice - Next teamplate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          <Container maxWidth="md">{children}</Container>
        </ClientProviders>
      </body>
    </html>
  );
}
